name: Dev Workflow

on:
  push:
    branches:
      - 'gen2*'
  pull_request:
    branches:
      - 'gen2*'

jobs:

  style:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install format dependencies
      run: |
        sudo apt-get install clang-format-10
        sudo apt-get install libusb-1.0-0-dev
        sudo apt-get install libusb-1.0-0

    - name: configure
      run: cmake . -Bbuild -DDEPTHAI_CLANG_FORMAT=ON -DCLANG_FORMAT_BIN=clang-format-10

    - name: check style
      run: ci/check_format.sh build


  tidy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      run: |
        sudo apt-get install clang-tidy-10
        sudo apt-get install libusb-1.0-0-dev
        sudo apt-get install libusb-1.0-0

    - name: configure
      run: cmake . -Bbuild -DDEPTHAI_CLANG_TIDY=ON -DCLANG_TIDY_BIN=clang-tidy-10

    - name: Run clang-tidy
      run: cmake --build build --parallel


  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
    
    - name: Install dependencies
      if: matrix.os == 'macos-latest'
      run: |
        brew install libusb

    - name: Install dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get install libusb-1.0-0-dev
        sudo apt-get install libusb-1.0-0

    - name: configure
      run: cmake . -Bbuild

    - name: build
      run: cmake --build build --parallel
